
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloSIBService", targetNamespace = "http://test/", wsdlLocation = "http://localhost:8080/soapSample?wsdl")
public class HelloSIBService
    extends Service
{

    private final static URL HELLOSIBSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOSIBSERVICE_EXCEPTION;
    private final static QName HELLOSIBSERVICE_QNAME = new QName("http://test/", "HelloSIBService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/soapSample?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOSIBSERVICE_WSDL_LOCATION = url;
        HELLOSIBSERVICE_EXCEPTION = e;
    }

    public HelloSIBService() {
        super(__getWsdlLocation(), HELLOSIBSERVICE_QNAME);
    }

    public HelloSIBService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOSIBSERVICE_QNAME, features);
    }

    public HelloSIBService(URL wsdlLocation) {
        super(wsdlLocation, HELLOSIBSERVICE_QNAME);
    }

    public HelloSIBService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOSIBSERVICE_QNAME, features);
    }

    public HelloSIBService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloSIBService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloSEI
     */
    @WebEndpoint(name = "HelloSIBPort")
    public HelloSEI getHelloSIBPort() {
        return super.getPort(new QName("http://test/", "HelloSIBPort"), HelloSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloSEI
     */
    @WebEndpoint(name = "HelloSIBPort")
    public HelloSEI getHelloSIBPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://test/", "HelloSIBPort"), HelloSEI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOSIBSERVICE_EXCEPTION!= null) {
            throw HELLOSIBSERVICE_EXCEPTION;
        }
        return HELLOSIBSERVICE_WSDL_LOCATION;
    }

}
